### ISSUE TITLE
Unable to parse chats

### ISSUE THREAD

**Issue by NetBender** [noe/whatsapp2md#1]
Hi. I've tried to run the script multiple times but every time I'm welcomed by the following error:
```bash
python3 whatsapp2md.py ../test.txt > ../test.md
Traceback (most recent call last):
  File "whatsapp2md.py", line 162, in <module>
    main()
  File "whatsapp2md.py", line 144, in main
    entries = parse_lines(f)
  File "whatsapp2md.py", line 124, in parse_lines
    raise ValueError(msg.format(lineno))
ValueError: Malformed file: line 1 is a continuation of no previous line
```

## Chat fragment (IT)

> 06/10/18, 10:56 - Me: PLorem ipsum dolor sit amet 😰
> 06/10/18, 11:05 - Myself: Lorem ipsum dolor sit amet
> 06/10/18, 11:05 - Myself: Lorem ipsum dolor sit amet
> 06/10/18, 11:06 - Myself: Lorem
> 06/10/18, 11:06 - Myself: Lorem ipsum dolor sit amet
> 06/10/18, 11:06 - Myself: Lorem ipsum dolor sit amet
> 06/10/18, 11:06 - Myself: Lorem
> 06/10/18, 11:07 - Myself: Lorem ipsum dolor sit amet
> 06/10/18, 11:07 - Myself: 🙄
> 06/10/18, 11:07 - Myself: PLorem ipsum dolor sit amet
> 06/10/18, 11:08 - Myself: Lorem ipsum dolor sit amet😅
>

**Comment by noe** [comment]
Sorry for taking soo long to answer. The issue notification passed unnoticed to me. It seems that the date format used by whatsapp has changed . I just fixed it. Please check with the latest version of whatsapp2md.

**Comment by NetBender** [comment]
Nevermind, it does work now and I thank you very much.
